{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "katalog") }}
{{- if include "fybrik.isEnabled" (tuple .Values.katalogConnector.enabled $autoFlag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katalog-connector
  labels:
    app.kubernetes.io/component: katalog-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.katalogConnector.autoscaling.enabled }}
  replicas: {{ .Values.katalogConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: katalog-connector
      {{- include "fybrik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.katalogConnector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fybrik.io/componentType: connector
        app.kubernetes.io/component: katalog-connector
        {{- include "fybrik.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.katalogConnector.serviceAccount.name }}
      securityContext:
      {{- include "fybrik.processPodSecurityContext" (dict "context" . "podSecurityContext" .Values.katalogConnector.podSecurityContext) | nindent 8 }}
      containers:
        - name: katalog-connector
          securityContext:
            {{- mergeOverwrite (deepCopy .Values.global.containerSecurityContext) .Values.katalogConnector.containerSecurityContext | toYaml | nindent 12 }}
          image: {{ include "fybrik.image" ( tuple $ .Values.katalogConnector ) }}
          imagePullPolicy: {{ .Values.katalogConnector.imagePullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.katalogConnector.resources | nindent 12 }}
          env:
            - name: DATA_DIR
              value: {{ include "fybrik.getDataDir" . }}
            - name: SERVICE_PORT
              value: {{ .Values.katalogConnector.service.port | quote }}
            - name: PRETTY_LOGGING
              value: {{ .Values.global.prettyLogging | quote }}
            - name: LOGGING_VERBOSITY
              value: {{ .Values.global.loggingVerbosity | quote }}
            - name: USE_TLS
              value: {{ .Values.katalogConnector.tls.use_tls | quote | toString }}
            - name: USE_MTLS
              value: {{ .Values.katalogConnector.tls.use_mtls | quote | toString }}
            - name: TLS_MIN_VERSION
              value: {{ .Values.katalogConnector.tls.minVersion }}
          volumeMounts:
            - name: data
              mountPath: {{ include "fybrik.getDataDir" . }}
            {{- if .Values.katalogConnector.tls.certs.certSecretName }}
            - mountPath: {{ include "fybrik.getDataSubdir" ( tuple "tls-cert" ) }}
              name: tls-cert
              readOnly: true
            {{- end }}
            {{- if .Values.katalogConnector.tls.certs.cacertSecretName }}
            - mountPath: {{ include "fybrik.getDataSubdir" ( tuple "tls-cacert" ) }}
              name: tls-cacert
              readOnly: true
            {{- end }}

      {{- with .Values.katalogConnector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.katalogConnector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.katalogConnector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir:
            sizeLimit: {{ .Values.katalogConnector.dirSizeLimit }}
        {{- if .Values.katalogConnector.tls.certs.certSecretName }}
        - name: tls-cert
          secret:
            defaultMode: 420
            secretName: {{ .Values.katalogConnector.tls.certs.certSecretName }}
        {{- end }}
        {{- if .Values.katalogConnector.tls.certs.cacertSecretName }}
        - name: tls-cacert
          secret:
            defaultMode: 420
            secretName: {{ .Values.katalogConnector.tls.certs.cacertSecretName }}
        {{- end }}

{{- end }}
