/*
Consolidate Services

Description of all APIs

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// V1Time Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.  +protobuf.options.marshal=false +protobuf.as=Timestamp +protobuf.options.(gogoproto.goproto_stringer)=false
type V1Time struct {
	// Non-negative fractions of a second at nanosecond resolution. Negative second values with fractions must still have non-negative nanos values that count forward in time. Must be from 0 to 999,999,999 inclusive. This field may be limited in precision depending on context.
	Nanos *int32 `json:"nanos,omitempty"`
	// Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
	Seconds *string `json:"seconds,omitempty"`
}

// NewV1Time instantiates a new V1Time object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1Time() *V1Time {
	this := V1Time{}
	return &this
}

// NewV1TimeWithDefaults instantiates a new V1Time object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1TimeWithDefaults() *V1Time {
	this := V1Time{}
	return &this
}

// GetNanos returns the Nanos field value if set, zero value otherwise.
func (o *V1Time) GetNanos() int32 {
	if o == nil || o.Nanos == nil {
		var ret int32
		return ret
	}
	return *o.Nanos
}

// GetNanosOk returns a tuple with the Nanos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Time) GetNanosOk() (*int32, bool) {
	if o == nil || o.Nanos == nil {
		return nil, false
	}
	return o.Nanos, true
}

// HasNanos returns a boolean if a field has been set.
func (o *V1Time) HasNanos() bool {
	if o != nil && o.Nanos != nil {
		return true
	}

	return false
}

// SetNanos gets a reference to the given int32 and assigns it to the Nanos field.
func (o *V1Time) SetNanos(v int32) {
	o.Nanos = &v
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *V1Time) GetSeconds() string {
	if o == nil || o.Seconds == nil {
		var ret string
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Time) GetSecondsOk() (*string, bool) {
	if o == nil || o.Seconds == nil {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *V1Time) HasSeconds() bool {
	if o != nil && o.Seconds != nil {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given string and assigns it to the Seconds field.
func (o *V1Time) SetSeconds(v string) {
	o.Seconds = &v
}

func (o V1Time) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Nanos != nil {
		toSerialize["nanos"] = o.Nanos
	}
	if o.Seconds != nil {
		toSerialize["seconds"] = o.Seconds
	}
	return json.Marshal(toSerialize)
}

type NullableV1Time struct {
	value *V1Time
	isSet bool
}

func (v NullableV1Time) Get() *V1Time {
	return v.value
}

func (v *NullableV1Time) Set(val *V1Time) {
	v.value = val
	v.isSet = true
}

func (v NullableV1Time) IsSet() bool {
	return v.isSet
}

func (v *NullableV1Time) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1Time(val *V1Time) *NullableV1Time {
	return &NullableV1Time{value: val, isSet: true}
}

func (v NullableV1Time) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1Time) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
