# Default values for Fybrik.
# This is a YAML-formatted file.
# It overrides values that are different from the default values.yaml

# Global configuration applies to multiple components installed by this chart
global:
  hub: localhost:5000/fybrik-system
  tag: "0.0.0"
  imagePullPolicy: "Always"

  prettyLogging: false
  # zerolog verbosity level 
  # ref: https://github.com/rs/zerolog#leveled-logging
  loggingVerbosity: -1

# Cluster metadata values
cluster:
  # Set to the name of the cluster.
  name: kind-control
  # Set to cluster zone.
  zone: baggin
  # Set to cluster region.
  region: took
  # Set to the cluster Vault auth method path.
  vaultAuthPath: control

# Configuration when deploying to a coordinator cluster.
coordinator:
  catalog: "katalog"
  vault:
    enabled: true
    # This is the public address of the nginx controller service in the control cluster.
    # Kind cluster maps port 80 to the listening port of the ingress controller by using
    # extraPortMappings and node-labels when creating the cluster.
    # ref: https://kind.sigs.k8s.io/docs/user/ingress/
    address: http://control-control-plane:80

  # Configures the Razee instance to be used by the coordinator manager in a multicluster setup
  razee:
    # URL for Razee local deployment
    url: "http://razeedash-api-lb.razee.svc.cluster.local:8081/graphql"
    # Usernane for Razee local deployment (dev only - fake login)
    user: "razee-dev@example.com"
    # Password for Razee local deployment (dev only - fake password)
    password: "password123"

# Manager component
manager:
  # Set to true to enable socat in the manager pod to forward
  # traffic from a localhost registry. Used only for development and integration tests.
  socat: true

