apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fybrik-kind-kind
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: 'kind-kind'
    namespace: fybrik-system
  source:
    path: charts/fybrik
    repoURL: 'https://github.com/fybrik/charts'
    targetRevision: HEAD
    helm:
      parameters:
        - name: cluster.name
          value: kind-kind
        - name: cluster.zone
          value: hobbiton
        - name: cluster.region
          value: theshire
        - name: cluster.vaultAuthPath
          value: kind
        - name: coordinator.enabled
          value: "false"
        - name: manager.socat
          value: "true"
        - name: global.hub
          value: localhost:5000/fybrik-system
        - name: global.tag
          value: "0.0.0"
  sources: []
  project: default
