vault:
  global:
    enabled: true

  standalone:
      enabled: true

  server:
    standalone:
      config: |
        plugin_directory = "/usr/local/libexec/vault"
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "file" {
          path = "/vault/data"
        }

    volumes:
      - name: plugins
        emptyDir: {}
    volumeMounts:
      - mountPath: /usr/local/libexec/vault
        name: plugins
        readOnly: false
    extraInitContainers:
      - name: kubesecrets-plugin
        image: ghcr.io/fybrik/vault-plugin-secrets-kubernetes-reader:0.5.0
        command: [/bin/sh, -ec]
        args:
          - cp /vault-plugin-secrets-kubernetes-reader /usr/local/libexec/vault/vault-plugin-secrets-kubernetes-reader
        volumeMounts:
        - name: plugins
          mountPath: /usr/local/libexec/vault
          readOnly: false
    # Used to define commands to run after the pod is ready.
    # This can be used to automate processes such as initialization
    # or boostrapping auth methods.
    postStart:
      - "sh"
      - "-c"
      # Sleep command is needed to avoid synchronization issues with the container pod. Please see
      # https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#discussion
      # FIXME: Use a proper way to configure Vault after Vault start-up
      - |
        sleep 5
        rm -rf /vault/data/*
        vault operator init | tee /tmp/vault.init > /dev/null
        cat /tmp/vault.init
        cat /tmp/vault.init | grep '^Unseal' | awk '{print $4}' | for key in $(cat -); do
          vault operator unseal $key
        done
        token=`cat /tmp/vault.init | grep 'Initial Root Token:' | awk '{print $4}'`; vault login $token
        SHA256=$(sha256sum /usr/local/libexec/vault/vault-plugin-secrets-kubernetes-reader | cut -d ' ' -f1) &&
        vault plugin register -sha256=$SHA256 secret vault-plugin-secrets-kubernetes-reader
        vault secrets enable -path=kubernetes-secrets vault-plugin-secrets-kubernetes-reader
