{{- if include "fybrik.isEnabled" (tuple .Values.manager.enabled .Values.coordinator.enabled) }}
{{- if include "fybrik.isArgocdConfigurationEnabled" . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-credentials
data:
  {{ if .Values.coordinator.argocd.url }}
  ARGOCD_URL: {{ .Values.coordinator.argocd.url | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.user }}
  ARGOCD_USER: {{ .Values.coordinator.argocd.user | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.password }}
  ARGOCD_PASSWORD: {{ .Values.coordinator.argocd.password | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.appsGitRepo.user }}
  ARGOCD_GIT_USER: {{ .Values.coordinator.argocd.appsGitRepo.user | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.appsGitRepo.password }}
  ARGOCD_GIT_PASSWORD: {{ .Values.coordinator.argocd.appsGitRepo.password | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.appsGitRepo.url }}
  ARGOCD_GIT_URL: {{ .Values.coordinator.argocd.appsGitRepo.url | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.fybrikAppsPrefix }}
  ARGOCD_FYBRIK_APPS_NAME_PREFIX: {{ .Values.coordinator.argocd.fybrikAppsPrefix | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.argocd.appsGitRepo.blueprintsAppsPath }}
  ARGOCD_GIT_BLUEPRINTS_APPS_PATH: {{ .Values.coordinator.argocd.appsGitRepo.blueprintsAppsPath | b64enc }}
  {{ end }}
{{- end }}
{{- end }}
