{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "m4d.fullname" . }}-metrics-service
  labels:
    {{- include "m4d.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
    {{- include "m4d.selectorLabels" . | nindent 4 }}
{{- end }}

