# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Kind cluster maps port 80 to the listening port of the ingress controller by using
  # extraPortMappings and node-labels when creating the cluster.
  # ref: https://kind.sigs.k8s.io/docs/user/ingress/
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80 # for Kind ingress
    hostPort: 80
    protocol: TCP
  - containerPort: 443 # for Kind ingress
    hostPort: 443
    protocol: TCP
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["http://kind-registry-proxy:5001"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-1.docker.io"]
    endpoint = ["http://kind-registry-proxy:5001"]
