{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-connector
  labels:
    app.kubernetes.io/component: opa-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.opaConnector.autoscaling.enabled }}
  replicas: {{ .Values.opaConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: opa-connector
      {{- include "fybrik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.opaConnector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fybrik.io/componentType: connector
        app.kubernetes.io/component: opa-connector
        {{- include "fybrik.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.opaConnector.serviceAccount.name }}
      securityContext:
      {{- include "fybrik.processPodSecurityContext" (dict "context" . "podSecurityContext" .Values.opaConnector.podSecurityContext) | nindent 8 }}
      containers:
        - name: opa-connector
          securityContext:
            {{- mergeOverwrite (deepCopy .Values.global.containerSecurityContext) .Values.opaConnector.containerSecurityContext | toYaml | nindent 12 }}
          image: {{ include "fybrik.image" ( tuple $ .Values.opaConnector ) }}
          imagePullPolicy: {{ .Values.opaConnector.imagePullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TLS_ENABLED
              value: {{ .Values.global.tls.enabled | quote | toString }}
            {{- if .Values.global.tls.enabled }}
            - name: MTLS_ENABLED
              value: {{ .Values.global.tls.mtlsEnabled | quote | toString }}
            - name: CERT_SECRET_NAME
              value: {{ .Values.opaConnector.tls.certs.serverCertSecretName }}
            - name: CERT_SECRET_NAMESPACE
              value: {{ .Values.opaConnector.tls.certs.serverCertSecretNamespace }}
            - name: CACERT_SECRET_NAME
              value: {{ .Values.opaConnector.tls.certs.cacertSecretName }}
            - name: CACERT_SECRET_NAMESPACE
              value: {{ .Values.opaConnector.tls.certs.cacertSecretNamespace }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: opa-connector-config
          resources:
            {{- toYaml .Values.opaConnector.resources | nindent 12 }}
      {{- with .Values.opaConnector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
