apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blueprints-kind-kind
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    name: 'kind-kind'
    namespace: fybrik-system
  source:
    path: blueprints/kind-kind
    repoURL: 'https://github.com/revit13/new-argocd-test1'
    targetRevision: HEAD
  sources: []
  project: fybrik

