name: Build

on:
  push:
    branches-ignore:
      - 'site'
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - 'releases/**'

env:
  GO_VERSION: 1.17
  # the newest supported K8s version and its respective kind image
  NEW_K8S_VERSION: v1.24.0@sha256:406fd86d48eaf4c04c7280cd1d2ca1d61e7d0d61ddef0125cb097bc7b82ed6a1
  # the oldest supported K8s version and its respective kind image
  OLD_K8S_VERSION: v1.22.9@sha256:6e57a6b0c493c7d7183a1151acff0bfa44bf37eb668826bf00da5637c55b6d5e 
  LATEST_BACKWARD_SUPPORTED_VERSION: 0.7.0

jobs:
  notebook-sample-read-flow-tls:
    name: Read flow notebook sample with tls
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: fybrik-system
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v3
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
          ${{ github.workspace }}/hack/tools/lib
        key: ${{ runner.os }}-c-${{ hashFiles('hack/make-rules/tools.mk') }}-${{ hashFiles('hack/tools/requirements.sh') }}-go-${{ hashFiles('**/go.sum') }}
    - name: Install tools
      run: make install-tools
    - name: Read flow notebook tests with tls
      run: make run-notebook-readflow-tls-tests

