name: Custom Build

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker Tag'
        required: true
        default: 'latest'

env:
  GO_VERSION: 1.17

jobs:
  build-and-publish:
    if: github.repository != 'fybrik/fybrik'
    name: Build and publish images
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "ghcr.io"
      DOCKER_NAMESPACE: ${{ github.actor }}
      DOCKER_TAG: ${{ github.event.inputs.dockerTag }}
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ github.token }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-custom
    - run: echo "Pushing images to ${DOCKER_HOSTNAME}/${DOCKER_NAMESPACE} from branch ${{ github.ref }}"
    - name: Build and push docker images
      run: make docker
    - name: Push helm charts
      run: make -C modules helm-chart-push